<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="51175" started-at="2019-05-21T11:55:46Z" finished-at="2019-05-21T11:56:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="51175" started-at="2019-05-21T11:55:46Z" finished-at="2019-05-21T11:56:37Z">
      <class name="selenium_intterview.Hashmap1">
        <test-method status="PASS" signature="Setup()[pri:0, instance:selenium_intterview.Hashmap1@59e5ddf]" name="Setup" is-config="true" duration-ms="13719" started-at="2019-05-21T11:55:46Z" finished-at="2019-05-21T11:55:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="FAIL" signature="loginfacebook()[pri:0, instance:selenium_intterview.Hashmap1@59e5ddf]" name="loginfacebook" duration-ms="35063" started-at="2019-05-21T11:55:59Z" finished-at="2019-05-21T11:56:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [ (2) Facebook] but found [(2) Facebook]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [ (2) Facebook] but found [(2) Facebook]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at selenium_intterview.Hashmap1.loginfacebook(Hashmap1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginfacebook -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:selenium_intterview.Hashmap1@59e5ddf]" name="TearDown" is-config="true" duration-ms="2331" started-at="2019-05-21T11:56:34Z" finished-at="2019-05-21T11:56:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- selenium_intterview.Hashmap1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
